### PR TITLE
Create Appointment Form

### PR DESCRIPTION
**Pull request by raw-chicken**
## Relevant Issue
[PAL-102](https://pallinet.atlassian.net/browse/PAL-102?atlOrigin=eyJpIjoiMTJhN2U0ZmI2ZjQ3NGVmZmFhZTk3MWQ0NDQxNWZkM2QiLCJwIjoiaiJ9)

## Description
Created a simple create appointment form that is connected to Firestore and will update the Firestore with the description, time created, and some other metadata.

## Work to be done
The form doesn't handle adding the people related to the appointment to Firestore yet and may need more fields to be added.

### CODE REVIEW

**Comment by Khoang4** [comment]
Looking good
Additional things to be added later:
Functionality to add a date to the appointment

**Comment by nrich9** [comment]
Good work

**Review by nrich9 — APPROVED** [review]
Great work. Looks great.

**Comment by Jacoonk** [comment]
UI for the Create Appointment Form looks good.

**Review by Jacoonk — APPROVED** [review]

**Pull request merged**
