### PR TITLE
Implement a unique ID when creating Patient

### PR DESCRIPTION
**Pull request by Khoang4**
## Relevant Issue
IDs were only 1111111 for all patients

## Description
Implemented a change in auth.dart that randomly generated a number between 1000000 - 9999999. A while loop then checks if this is unique within the database and if it is, breaks and assigns it to the patient. otherwise it will randomly generate again until it is stopped by a checker or is unique.

### CODE REVIEW

**Review by raw-chicken — COMMENTED** [review]
Decent temporary solution, though we probably don't want this as our final solution.

Still thinking of having the IDs for patients be marked by some letter like `PA-1123434` or something, so that it can be distinguishable from Physicians for the chats / appointments.

Additionally, I thought we were going to index from 1, and assign numerically (since Firestore now has a cheap function for counting number of patients).

**Comment by Khoang4** [comment]
I can make those changes to it. Adding in the letter is a pretty easy fix as well. I totally forgot about counting from 1 not going to lie and incorporated it starting from 1000000 so that it retained a 7 digit length

**Comment by raw-chicken** [comment]
You can start from 1000000, but since we're storing it as a string, you probably can start from 0000000 and just do string manipulation do append 0s, but either way is fine.

Specifically talking abuot `padLeft` see [here](https://www.cloudhadoop.com/dart-leading-trailing-zero-number/#:~:text=There%20are%20several%20ways%20to%20add%20pad%20zeroes,padLeft%20%28int%20width%2C%20%5BString%20padding%20%3D%20%27%20%27%5D%29).

**Comment by raw-chicken** [comment]
There's actually a specific function for counting documents. The current method works but doesn't scale well since we would have to read every single document which counts as individual reads. See [this](https://stackoverflow.com/a/74426843/20850976), it's basically the same just costs less in terms of database usage.

**Comment by Khoang4** [comment]
Ah I see. I was trying to get the .count() to work earlier on when I was doing the while loop checking but the documentation on the website was old and it used getCount() instead which confused me. Thanks!

**Review by Jacoonk — APPROVED** [review]
Good job on creating a unique ID for creating a new patient.

**Pull request merged**
