### PR TITLE
Create UI and Navigation for Detailed Patient Information

### PR DESCRIPTION
**Pull request by Jacoonk**
## Relevant Issue
[PAL-73] (https://pallinet.atlassian.net/browse/PAL-73?atlOrigin=eyJpIjoiMTA2MTYzOGQzNmNjNDA2NjlhYzMyNzlmYWIxYWJkMTAiLCJwIjoiaiJ9)
[PAL- 103] (https://pallinet.atlassian.net/browse/PAL-103?atlOrigin=eyJpIjoiYTU3ZmNhNDk0NmNjNDAxMmJmMzFjMzgzZDFmOGU3NDciLCJwIjoiaiJ9)
## Description
I created the Navigation to the detailed Patient Information View. 
I created the UI for the detailed Patient Information View.

### CODE REVIEW

**Comment by jlei46** [comment]
Can see the patient detail list, summary list, and physician home page. Looks good to me!

**Comment by brandon-zhou** [comment]
New view looks good, can likely further refine the UI in future sprints

**Comment by nrich9** [comment]
Great work. UI looks nice.

**Review by brandon-zhou — APPROVED** [review]
New view looks good, can likely further refine the UI in future sprints

**Review by nrich9 — APPROVED** [review]
Good work.

**Review by jlei46 — APPROVED** [review]
Looks fine to me. Can see physician page with detailed view.

**Pull request merged**
