### PR TITLE
update Treatments

### PR DESCRIPTION
**Pull request by nrich9**
## Relevant Issue
[PAL-124] https://pallinet.atlassian.net/browse/PAL-124

## Description
added treatments database. 
use when testing:
user: johnsmith@gmail.com
password: password

### CODE REVIEW

**Review by Jacoonk — CHANGES_REQUESTED** [review]
Change the variable names so that they are all Camel cased so it stays consistent with our naming convention and make sure all class names are Pascal Cased class "treatmentsRecommended" --> "TreatmentsRecommended'. Good job on the code itself, I think we may add more to treatments view and treatments card but just make sure your naming conventions are consistent with ours.

**Comment by nrich9** [comment]
thank you for the feedback. Changes to naming convention have been implemented. Will keep in mind for next commits

**Review by Jacoonk — APPROVED** [review]
Good job on implementing the changes.

**Review by brandon-zhou — APPROVED** [review]
looks good, good foundation for the treatment setup

**Pull request merged**
